From nginx 
Run rm -rf /usr/share/nginx/html/index.html
Run rm -rf /etc/nginx/nginx.conf
Run rm -rf /etc/nginx/conf.d/default.conf
Copy default.conf /etc/nginx/nginx.conf
Add static /usr/share/nginx/html/
Env catalogue_HOST="catalogue"